import { Injectable } from '@angular/core';
import { Card } from './app.component';

@Injectable({
  providedIn: 'root',
})
export class HandsService {
  getHands(): Card[][] {
    return [
      [
        { letter: 'AA', clicked: false },
        { letter: 'AKs', clicked: false },
        { letter: 'AQs', clicked: false },
        { letter: 'AJs', clicked: false },
        { letter: 'A10s', clicked: false },
        { letter: 'A9s', clicked: false },
        { letter: 'A8s', clicked: false },
        { letter: 'A7s', clicked: false },
        { letter: 'A6s', clicked: false },
        { letter: 'A5s', clicked: false },
        { letter: 'A4s', clicked: false },
        { letter: 'A3s', clicked: false },
        { letter: 'A2s', clicked: false },
      ],
      [
        { letter: 'AK', clicked: false },
        { letter: 'KK', clicked: false },
        { letter: 'KQs', clicked: false },
        { letter: 'KJs', clicked: false },
        { letter: 'K10s', clicked: false },
        { letter: 'K9s', clicked: false },
        { letter: 'K8s', clicked: false },
        { letter: 'K7s', clicked: false },
        { letter: 'K6s', clicked: false },
        { letter: 'K5s', clicked: false },
        { letter: 'K4s', clicked: false },
        { letter: 'K3s', clicked: false },
        { letter: 'K2s', clicked: false },
      ],
      [
        { letter: 'AQ', clicked: false },
        { letter: 'KQ', clicked: false },
        { letter: 'QQ', clicked: false },
        { letter: 'QJs', clicked: false },
        { letter: 'Q10s', clicked: false },
        { letter: 'Q9s', clicked: false },
        { letter: 'Q8s', clicked: false },
        { letter: 'Q7s', clicked: false },
        { letter: 'Q6s', clicked: false },
        { letter: 'Q5s', clicked: false },
        { letter: 'Q4s', clicked: false },
        { letter: 'Q3s', clicked: false },
        { letter: 'Q2s', clicked: false },
      ],
      [
        { letter: 'AJ', clicked: false },
        { letter: 'KJ', clicked: false },
        { letter: 'QJ', clicked: false },
        { letter: 'JJ', clicked: false },
        { letter: 'J10s', clicked: false },
        { letter: 'J9s', clicked: false },
        { letter: 'J8s', clicked: false },
        { letter: 'J7s', clicked: false },
        { letter: 'J6s', clicked: false },
        { letter: 'J5s', clicked: false },
        { letter: 'J4s', clicked: false },
        { letter: 'J3s', clicked: false },
        { letter: 'J2s', clicked: false },
      ],
      [
        { letter: 'A10', clicked: false },
        { letter: 'K10', clicked: false },
        { letter: 'Q10', clicked: false },
        { letter: 'J10', clicked: false },
        { letter: '1010', clicked: false },
        { letter: '109s', clicked: false },
        { letter: '108s', clicked: false },
        { letter: '107s', clicked: false },
        { letter: '106s', clicked: false },
        { letter: '105s', clicked: false },
        { letter: '104s', clicked: false },
        { letter: '103s', clicked: false },
        { letter: '102s', clicked: false },
      ],
      [
        { letter: 'A9', clicked: false },
        { letter: 'K9', clicked: false },
        { letter: 'Q9', clicked: false },
        { letter: 'J9', clicked: false },
        { letter: '109', clicked: false },
        { letter: '99', clicked: false },
        { letter: '98s', clicked: false },
        { letter: '97s', clicked: false },
        { letter: '96s', clicked: false },
        { letter: '95s', clicked: false },
        { letter: '94s', clicked: false },
        { letter: '93s', clicked: false },
        { letter: '92s', clicked: false },
      ],
      [
        { letter: 'A8', clicked: false },
        { letter: 'K8', clicked: false },
        { letter: 'Q8', clicked: false },
        { letter: 'J8', clicked: false },
        { letter: '108', clicked: false },
        { letter: '98', clicked: false },
        { letter: '88', clicked: false },
        { letter: '87s', clicked: false },
        { letter: '86s', clicked: false },
        { letter: '85s', clicked: false },
        { letter: '84s', clicked: false },
        { letter: '83s', clicked: false },
        { letter: '82s', clicked: false },
      ],
      [
        { letter: 'A7', clicked: false },
        { letter: 'K7', clicked: false },
        { letter: 'Q7', clicked: false },
        { letter: 'J7', clicked: false },
        { letter: '107', clicked: false },
        { letter: '97', clicked: false },
        { letter: '87', clicked: false },
        { letter: '77', clicked: false },
        { letter: '76s', clicked: false },
        { letter: '75s', clicked: false },
        { letter: '74s', clicked: false },
        { letter: '73s', clicked: false },
        { letter: '72s', clicked: false },
      ],
      [
        { letter: 'A6', clicked: false },
        { letter: 'K6', clicked: false },
        { letter: 'Q6', clicked: false },
        { letter: 'J6', clicked: false },
        { letter: '106', clicked: false },
        { letter: '96', clicked: false },
        { letter: '86', clicked: false },
        { letter: '76', clicked: false },
        { letter: '66', clicked: false },
        { letter: '65s', clicked: false },
        { letter: '64s', clicked: false },
        { letter: '63s', clicked: false },
        { letter: '62s', clicked: false },
      ],
      [
        { letter: 'A5', clicked: false },
        { letter: 'K5', clicked: false },
        { letter: 'Q5', clicked: false },
        { letter: 'J5', clicked: false },
        { letter: '105', clicked: false },
        { letter: '95', clicked: false },
        { letter: '85', clicked: false },
        { letter: '75', clicked: false },
        { letter: '65', clicked: false },
        { letter: '55', clicked: false },
        { letter: '54s', clicked: false },
        { letter: '53s', clicked: false },
        { letter: '52s', clicked: false },
      ],
      [
        { letter: 'A4', clicked: false },
        { letter: 'K4', clicked: false },
        { letter: 'Q4', clicked: false },
        { letter: 'J4', clicked: false },
        { letter: '104', clicked: false },
        { letter: '94', clicked: false },
        { letter: '84', clicked: false },
        { letter: '74', clicked: false },
        { letter: '64', clicked: false },
        { letter: '54', clicked: false },
        { letter: '44', clicked: false },
        { letter: '43s', clicked: false },
        { letter: '42s', clicked: false },
      ],
      [
        { letter: 'A3', clicked: false },
        { letter: 'K3', clicked: false },
        { letter: 'Q3', clicked: false },
        { letter: 'J3', clicked: false },
        { letter: '103', clicked: false },
        { letter: '93', clicked: false },
        { letter: '83', clicked: false },
        { letter: '73', clicked: false },
        { letter: '63', clicked: false },
        { letter: '53', clicked: false },
        { letter: '43', clicked: false },
        { letter: '33', clicked: false },
        { letter: '32s', clicked: false },
      ],
      [
        { letter: 'A2', clicked: false },
        { letter: 'K2', clicked: false },
        { letter: 'Q2', clicked: false },
        { letter: 'J2', clicked: false },
        { letter: '102', clicked: false },
        { letter: '92', clicked: false },
        { letter: '82', clicked: false },
        { letter: '72', clicked: false },
        { letter: '62', clicked: false },
        { letter: '52', clicked: false },
        { letter: '42', clicked: false },
        { letter: '32', clicked: false },
        { letter: '22', clicked: false },
      ],
    ];
  }

  constructor() {}
}
